### ISSUE TITLE
Unable to load the requested language file: language/American-English/ip_lang.php

### ISSUE THREAD

**Issue by cachho** [InvoicePlane/InvoicePlane#1233]
### Title

Folder in application/language is called `english` not `American-English`

### Expected Behavior

names to match

### Steps to Reproduce

1. set browser language to `en-US`
2. finish setup

### Screenshots (Optional)

![Image](https://github.com/user-attachments/assets/0a150493-0f4c-4c80-8d5a-6066c7cef9f1)

### Possible Solution (Optional)

Copy `english` as `American-English`

### Context (Environment)

```yaml
version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

networks:
  nginx-proxy-manager-network:
    name: nginx-proxy-manager-network
    external: true
    driver: bridge
  internal-net:
    name: internal-net
    driver: bridge

volumes:
  invoiceplane_data:
  invoiceplane_mariadb_10_4:

services:
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:latest
    restart: always
    volumes:
      - invoiceplane_data:/var/www/html/uploads
      - /export/nas/invoiceplane/ipconfig.php:/var/www/html/ipconfig.php
      - /export/nas/invoiceplane/InvoicePlane.php:/var/www/html/application/views/invoice_templates/pdf/InvoicePlane.php
    # command: echo "hello world"

    ports:
      - 80
    networks:
      - nginx-proxy-manager-network
      - internal-net
    env_file: stack.env
    depends_on:
      - invoiceplane_mariadb

  invoiceplane_mariadb:
    # MySQL 5.7
    container_name: invoiceplane_mariadb
    image: mariadb:10.4.10
    restart: always
    volumes:
      - invoiceplane_mariadb_10_4:/var/lib/mysql
    env_file: stack.env
    networks:
      - internal-net
    ports:
      - 3306
```

### Failure Logs (Optional)

nothing in the logs
