### ISSUE TITLE
Incorrect table row alignment

### ISSUE THREAD

**Issue by nsina** [InvoicePlane/InvoicePlane#43]
The following code is pushing the table rows up instead of keeping them centered. 
See `vertical-align`

Pages: View clients, View Quotes, View Invoices etc.

``` css
.table>thead>tr>th, 
.table>thead>tr>td, 
.table>tbody>tr>th, 
.table>tbody>tr>td, 
.table>tfoot>tr>th, 
.table>tfoot>tr>td {
...
vertical-align: top;
...
}
```
