### ISSUE TITLE
Fix Datepicker dropdown padding

### ISSUE THREAD

**Issue by nsina** [InvoicePlane/InvoicePlane#45]
Change from 

``` css
.dropdown-menu {
...
padding: 5px 0;
...
```

 to

``` css
.dropdown-menu {
...
padding: 5px;
...
}
```
