### ISSUE TITLE
Fix margin on top of the alert box

### ISSUE THREAD

**Issue by nsina** [InvoicePlane/InvoicePlane#55]
Add margin on top of the `.alert` (under the border-bottom of the header)

~~margin-bottom: 20px;~~

Change to:

``` css
.alert {
...
margin: 20px 0;
...
}
```

![img](https://cloud.githubusercontent.com/assets/4546547/3883170/ac7d9414-219e-11e4-98e2-2005e433bafb.PNG)
